CREATE DATABASE GESTOR_DE_TURNOS
GO
USE GESTOR_DE_TURNOS
GO

CREATE TABLE CATEGORIAS(
    IDCATEGORIA TINYINT PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(150) NULL
)
GO

CREATE TABLE ESPECIALIDADES(
    IDESPECIALIDAD TINYINT PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(50) NOT NULL,
    RAMA VARCHAR(100) NOT NULL
)
GO
