CREATE DATABASE GESTOR_DE_TURNOS
GO
USE GESTOR_DE_TURNOS
GO

CREATE TABLE CATEGORIAS(
    IDCATEGORIA TINYINT PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(150) NULL
)
GO

CREATE TABLE ESPECIALIDADES(
    IDESPECIALIDAD TINYINT PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(50) NOT NULL,
    RAMA VARCHAR(100) NOT NULL
)
GO

CREATE TABLE PROVINCIAS(
    IDPROVINCIA TINYINT PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(60) NOT NULL
)
GO

CREATE TABLE CIUDADES(
    IDCIUDAD TINYINT PRIMARY KEY IDENTITY(1,1),
    IDPROVINCIA TINYINT NOT NULL,
    NOMBRE VARCHAR(60) NOT NULL
)
GO
ALTER TABLE CIUDADES
ADD CONSTRAINT FK_CIU_PROV FOREIGN KEY (IDPROVINCIA) REFERENCES PROVINCIAS(IDPROVINCIA)
GO

CREATE TABLE DOMICILIOS(
    IDDOMICILIO TINYINT PRIMARY KEY IDENTITY(1,1),
    CALLE VARCHAR(60) NOT NULL,
    ALTURA INT NOT NULL,
    IDCIUDAD TINYINT NOT NULL,
    CODPOSTAL INT NULL
)
GO
ALTER TABLE DOMICILIOS
ADD CHECK(ALTURA > 0)
GO
ALTER TABLE DOMICILIOS
ADD CONSTRAINT FK_DOMI_CIU FOREIGN KEY (IDCIUDAD) REFERENCES CIUDADES(IDCIUDAD)
GO
ALTER TABLE DOMICILIOS
ADD CHECK(CODPOSTAL > 0)
GO

CREATE TABLE PERSONAS(
    DNI INT PRIMARY KEY,
    NOMBRE VARCHAR(60) NOT NULL,
    APELLIDO VARCHAR(60) NOT NULL,
    SEXO CHAR NULL,
    FECHANACIMIENTO DATE NOT NULL,
    IDDOMICILIO TINYINT NOT NULL
)
GO
ALTER TABLE PERSONAS
ADD CHECK(DNI > 1111111)
GO
ALTER TABLE PERSONAS
ADD CHECK(SEXO = 'F' OR SEXO = 'M')
GO
ALTER TABLE PERSONAS
ADD CHECK(FECHANACIMIENTO <= GETDATE())
GO
ALTER TABLE PERSONAS
ADD CONSTRAINT FK_PER_DOMI FOREIGN KEY (IDDOMICILIO) REFERENCES DOMICILIOS(IDDOMICILIO)
GO

CREATE TABLE COBERTURAS(
    IDCOBERTURA TINYINT PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(60) NOT NULL
)
GO

CREATE TABLE PACIENTES(
    NUMPACIENTE INT PRIMARY KEY IDENTITY(1,1),
    DNIPERSONA INT NOT NULL,
    FECHAAFILIACION DATE NOT NULL,
    IDCOBERTURA TINYINT NOT NULL
)
GO
ALTER TABLE PACIENTES
ADD CONSTRAINT UNICO_PACIENTE UNIQUE(DNIPERSONA)
GO
ALTER TABLE PACIENTES
ADD CONSTRAINT FK_PACI_PER FOREIGN KEY (DNIPERSONA) REFERENCES PERSONAS(DNI)
GO
ALTER TABLE PACIENTES
ADD CHECK(FECHAAFILIACION <= GETDATE())
GO
ALTER TABLE PACIENTES
ADD CONSTRAINT FK_PACI_COBER FOREIGN KEY (IDCOBERTURA) REFERENCES COBERTURAS(IDCOBERTURA)
GO

CREATE TABLE MEDICOS(
    NUMMATRICULA INT PRIMARY KEY,
    DNIPERSONA INT NOT NULL,
    IDESPECIALIDAD TINYINT NOT NULL,
    ESTADO BIT NOT NULL DEFAULT(1)
)
GO
ALTER TABLE MEDICOS
ADD CONSTRAINT FK_MED_PER FOREIGN KEY (DNIPERSONA) REFERENCES PERSONAS(DNI)
GO
ALTER TABLE MEDICOS
ADD CONSTRAINT FK_MED_ESP FOREIGN KEY (IDESPECIALIDAD) REFERENCES ESPECIALIDADES(IDESPECIALIDAD)
GO

CREATE TABLE TURNOS(
    IDTURNO INT PRIMARY KEY IDENTITY(1,1),
    NUMPACIENTE INT NOT NULL,
    MATRICULAMEDICO INT NOT NULL,
    IDCATTURNO TINYINT NOT NULL,
    IDESPECIALIDAD TINYINT NOT NULL,
    FECHAHORATURNO DATETIME NOT NULL
)
GO
ALTER TABLE TURNOS
ADD CONSTRAINT FK_TUR_PACI FOREIGN KEY (NUMPACIENTE) REFERENCES PACIENTES(NUMPACIENTE)
GO
ALTER TABLE TURNOS
ADD CONSTRAINT FK_TUR_MED FOREIGN KEY (MATRICULAMEDICO) REFERENCES MEDICOS(NUMMATRICULA)
GO
ALTER TABLE TURNOS
ADD CONSTRAINT FK_TUR_CAT FOREIGN KEY (IDCATTURNO) REFERENCES CATEGORIAS(IDCATEGORIA)
GO
ALTER TABLE TURNOS
ADD CONSTRAINT FK_TUR_ESP FOREIGN KEY (IDESPECIALIDAD) REFERENCES ESPECIALIDADES(IDESPECIALIDAD)
GO
ALTER TABLE TURNOS
ADD CHECK(FECHAHORATURNO >= GETDATE())
GO